name: lint test and deploy
on: push
jobs:
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: read directory
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies packages
        run: npm install

      - name: test
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying...."

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: read directory
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies packages
        run: npm install

      - name: run lint
        run: npm run lint
